prefixes = [
    "re",
    "dis",
    "over",
    "un",
    "mis",
    "out",
    "co",
    "de",
    "fore",
    "inter",
    "pre",
    "sub",
    "trans",
    "under",
    "anti",
    "auto",
    "bi",
    "counter",
    "ex",
    "hyper",
    "kilo",
    "mal",
    "mega",
    "mini",
    "mono",
    "neo",
    "poly",
    "pseudo",
    "semi",
    "sur",
    "tele",
    "tri",
    "ultra",
    "vice",
    "non",
    # "super",  # consider "super" as intensifier
]

prefix_trigram_base_word_pos = [
    "ADJ",
    "ADV",
    "VERB",
    "NOUN",
]

ampersand_trigram_word_pos = [
    "ADJ", 
    "NOUN", 
    "PROPN",
]

hyphen_trigram_two_words_pos = [
    ("NOUN", "NOUN"),
    ("NOUN", "ADJ"),
    ("ADJ", "ADJ"),
    ("ADV", "ADJ"),
    ("ADV", "VERB"),
]

hyphen_trigram_blacklist = [
    "day - old",
    "days - old",
    "week - old",
    "weeks - old",
    "month - old",
    "months - old",
    "year - old",
    "years - old",
]

intensifiers = {
    "kind of": -0.3,
    "sort of": -0.3,
    "just enough": -0.3,
    "bit": -0.3,
    "less": -0.3,
    "little": -0.3,
    "slight": -0.3,
    "slightly": -0.3,
    "somewhat": -0.3,
    "almost": -0.3,
    "barely": -0.3,
    "hardly": -0.3,
    "kinda": -0.3,
    "kindof": -0.3,
    "marginal": -0.3,
    "marginally": -0.3,
    "occasional": -0.3,
    "occasionally": -0.3,
    "partly": -0.3,
    "scarce": -0.3,
    "scarcely": -0.3,
    "sorta": -0.3,
    "sortof": -0.3,
    "absolutely": 0.3,
    "absurdly": 0.3,
    "amazingly": 0.3,
    "awfully": 0.3,
    "beyond": 0.3,
    "big": 0.3,
    "certainly": 0.3,
    "completely": 0.3,
    "enormously": 0.3,
    "entirely": 0.3,
    "especially": 0.3,
    "extremely": 0.3,
    "fully": 0.3,
    "highly": 0.3,
    "huge": 0.3,
    "hugely": 0.3,
    "incredibly": 0.3,
    "intensely": 0.3,
    "most": 0.3,
    "much": 0.3,
    "particularly": 0.3,
    "perfectly": 0.3,
    "pretty": 0.3,
    "quite": 0.3,
    "rather": 0.3,
    "really": 0.3,
    "remarkably": 0.3,
    "resoundingly": 0.3,
    "so": 0.3,
    "spectacularly": 0.3,
    "strikingly": 0.3,
    "strongly": 0.3,
    "super": 0.3,
    "surprisingly": 0.3,
    "terribly": 0.3,
    "thoroughly": 0.3,
    "too": 0.3,
    "totally": 0.3,
    "tremendously": 0.3,
    "unbelievably": 0.3,
    "unusually": 0.3,
    "utterly": 0.3,
    "very": 0.3,
    "considerable": 0.3,
    "considerably": 0.3,
    "decidedly": 0.3,
    "deeply": 0.3,
    "effing": 0.3,
    "enormous": 0.3,
    "exceptional": 0.3,
    "exceptionally": 0.3,
    "extreme": 0.3,
    "fabulously": 0.3,
    "flipping": 0.3,
    "flippin": 0.3,
    "frackin": 0.3,
    "fracking": 0.3,
    "fricking": 0.3,
    "frickin": 0.3,
    "frigging": 0.3,
    "friggin": 0.3,
    "fuckin": 0.3,
    "fucking": 0.3,
    "fuggin": 0.3,
    "fugging": 0.3,
    "greatly": 0.3,
    "hella": 0.3,
    "incredible": 0.3,
    "major": 0.3,
    "majorly": 0.3,
    "more": 0.3,
    "purely": 0.3,
    "substantially": 0.3,
    "total": 0.3,
    "tremendous": 0.3,
    "utter": 0.3,
}